package storage

import "gorm.io/gorm"

func runMigrations(db *gorm.DB) error {
	return db.AutoMigrate(
		&Server{},
		&ServerProfile{},
		&ServerMetricSnapshot{},
		&MetricSample{},
		&ErrorEvent{},
		&AlertRule{},
		&DeployHistory{},
		&AISession{},
		&Backup{},
		&BackupDestination{},
		&ActivityLog{},
		&SecurityEvent{},
		&RequestDump{},
		&SecurityPolicy{},
		&TrafficHit{},
		&AIConfigRecord{},
		&User{},
		&Project{},
		&ProjectDomain{},
		&ProjectEnvVar{},
		&GitCredential{},
		&GitOAuthApp{},
		&CronJob{},
		&CronRun{},
		&UptimeMonitor{},
		&UptimeEvent{},
		&AlertChannel{},
		&ServiceInstance{},
		&RecipeInstall{},
		&ScriptRun{},
		&DatabaseUser{},
		&ConnectedDomain{},
		&NodeSettings{},
		&Mailbox{},
		&ProjectDatabase{},
		&FTPUser{},
		&StorageBucket{},
	)
}
